index:
    path: /
    controller: App\Controller\HomeController::index

about:
    path: /about
    controller: App\Controller\aboutController::index

gallery:
    path: /gallery
    controller: App\Controller\galleryController::index

project:
    path: /gallery/project/{id}
    controller: App\Controller\projectController::index

contact:
    path: /contact
    controller: App\Controller\contactController::index

admin:
    path: /admin
    controller: App\Controller\adminController::index

adminProjects:
    path: /admin/projects
    controller: App\Controller\adminProjectsController::index

adminProject:
    path: /admin/project/{id}
    controller: App\Controller\showProjectController::index
